# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/providersRegistration2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1385, 963)
        Form.setStyleSheet("#lineFake, #lineEditTelefonoEmpresa_2{\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"background-color:transparent;\n"
"border:none;\n"
"}\n"
"#comboBox{\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"border:none;\n"
"}\n"
"#mainWindow {\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#labelAdd{\n"
"    font-size:24px;\n"
"}\n"
"\n"
"#menu {\n"
"    background: #eee;\n"
"    border-bottom: 1.5px solid #bdbdbd;\n"
"}\n"
"\n"
"#menu QLabel {\n"
"    font-size: 16px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#menu QWidget:hover {\n"
"    background: #e0e0e0;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] {\n"
"    background: #ffffff;\n"
"    border-bottom: 3px solid #487c7e;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] QLabel {\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#menu QWidget {\n"
"    border-right: 1px solid #bdbdbd;\n"
"    border-left: 1px solid #bdbdbd;\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #487c7e;\n"
"}\n"
"\n"
"QLabel#labelTituloProveedores{\n"
"    font-size: 36px;\n"
"    font-weight: 600;\n"
"    color: #222;\n"
"}\n"
"\n"
"QPushButton#btnAdd {\n"
"    background: transparent;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"    border: none;\n"
"}\n"
"QPushButton#btnAdd:hover {\n"
"    color: #444;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QToolButton:hover {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#btnBack {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"}\n"
"QPushButton#btnBack:hover {\n"
"    color: #555;\n"
"}\n"
"\n"
"\n"
"QTableWidget {\n"
"    background: #eee;\n"
"    gridline-color: transparent;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    color: #222;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #eee;\n"
"    padding: 6px 4px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #b4b4b4;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: #c6d3d6;\n"
"    color: #000;\n"
"}\n"
"\n"
"QScrollBar:vertical,\n"
"QScrollBar:horizontal {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #aaaaaa;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    background: #888888;\n"
"}\n"
"\n"
"#tablaContenedor {\n"
"    background: #7835ff;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto,\n"
"QPushButton#btnRemoveProducto {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto:hover,\n"
"QPushButton#btnRemoveProducto:hover {\n"
"    color: #487c7e;\n"
"}\n"
"\n"
"QPushButton#btnCancelar {\n"
"    background: #e7b0b0;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnCancelar:hover {\n"
"    background: #d59a9a;\n"
"}\n"
"\n"
"QPushButton#btnGuardar {\n"
"    background: #b9e3a6;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnGuardar:hover {\n"
"    background: #a3d68c;\n"
"}\n"
"\n"
"#panelRegistro {\n"
"    background: #e0e0e0;\n"
"    border-radius: 8px;\n"
"    border: 1.5px solid #b8b8b8;\n"
"    padding: 16px;\n"
"}\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTituloProveedores = QtWidgets.QLabel(Form)
        self.labelTituloProveedores.setObjectName("labelTituloProveedores")
        self.horizontalLayout_2.addWidget(self.labelTituloProveedores)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.panelRegistro = QtWidgets.QWidget(Form)
        self.panelRegistro.setObjectName("panelRegistro")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panelRegistro)
        self.horizontalLayout_4.setSpacing(45)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.labelDatos = QtWidgets.QLabel(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDatos.sizePolicy().hasHeightForWidth())
        self.labelDatos.setSizePolicy(sizePolicy)
        self.labelDatos.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelDatos.setFont(font)
        self.labelDatos.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelDatos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDatos.setObjectName("labelDatos")
        self.verticalLayout_4.addWidget(self.labelDatos)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(60, -1, 60, -1)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.panelRegistro)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox = QtWidgets.QComboBox(self.panelRegistro)
        self.comboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox.setStyleSheet(" text-align: center;\n"
"color:black;\n"
"background-color:white;\n"
"")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.lineEditRIFEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRIFEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditRIFEmpresa.setSizePolicy(sizePolicy)
        self.lineEditRIFEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditRIFEmpresa.setObjectName("lineEditRIFEmpresa")
        self.horizontalLayout_6.addWidget(self.lineEditRIFEmpresa)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.label_11 = QtWidgets.QLabel(self.panelRegistro)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.lineEditNameEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNameEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditNameEmpresa.setSizePolicy(sizePolicy)
        self.lineEditNameEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditNameEmpresa.setObjectName("lineEditNameEmpresa")
        self.verticalLayout_7.addWidget(self.lineEditNameEmpresa)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.label_12 = QtWidgets.QLabel(self.panelRegistro)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.lineEditDireccionEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDireccionEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditDireccionEmpresa.setSizePolicy(sizePolicy)
        self.lineEditDireccionEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditDireccionEmpresa.setObjectName("lineEditDireccionEmpresa")
        self.verticalLayout_7.addWidget(self.lineEditDireccionEmpresa)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(6, 1)
        self.verticalLayout_7.setStretch(9, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.label_5 = QtWidgets.QLabel(self.panelRegistro)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineEditTelefonoEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTelefonoEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditTelefonoEmpresa.setSizePolicy(sizePolicy)
        self.lineEditTelefonoEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditTelefonoEmpresa.setObjectName("lineEditTelefonoEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditTelefonoEmpresa)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.panelRegistro)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.lineEditCorreoEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCorreoEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditCorreoEmpresa.setSizePolicy(sizePolicy)
        self.lineEditCorreoEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditCorreoEmpresa.setObjectName("lineEditCorreoEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditCorreoEmpresa)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.panelRegistro)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.lineEditTelefonoEmpresa_2 = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTelefonoEmpresa_2.sizePolicy().hasHeightForWidth())
        self.lineEditTelefonoEmpresa_2.setSizePolicy(sizePolicy)
        self.lineEditTelefonoEmpresa_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditTelefonoEmpresa_2.setPlaceholderText("")
        self.lineEditTelefonoEmpresa_2.setObjectName("lineEditTelefonoEmpresa_2")
        self.verticalLayout_5.addWidget(self.lineEditTelefonoEmpresa_2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.verticalLayout_5.setStretch(6, 1)
        self.verticalLayout_5.setStretch(9, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout_4.setStretch(2, 5)
        self.verticalLayout_4.setStretch(3, 75)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.panelRegistro)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(250, -1, 250, 0)
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnCancelar = QtWidgets.QPushButton(Form)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        self.btnGuardar = QtWidgets.QPushButton(Form)
        self.btnGuardar.setObjectName("btnGuardar")
        self.horizontalLayout_5.addWidget(self.btnGuardar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 10)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTituloProveedores.setText(_translate("Form", "Registro de proveedores"))
        self.labelDatos.setText(_translate("Form", "Datos de la empresa"))
        self.label_7.setText(_translate("Form", "RIF"))
        self.comboBox.setItemText(0, _translate("Form", "V"))
        self.comboBox.setItemText(1, _translate("Form", "J"))
        self.comboBox.setItemText(2, _translate("Form", "G"))
        self.lineEditRIFEmpresa.setPlaceholderText(_translate("Form", "Correo"))
        self.label_11.setText(_translate("Form", "Nombre de la Empresa"))
        self.lineEditNameEmpresa.setPlaceholderText(_translate("Form", "Teléfono"))
        self.label_12.setText(_translate("Form", "Dirección de la Empresa"))
        self.lineEditDireccionEmpresa.setPlaceholderText(_translate("Form", "Teléfono"))
        self.label_5.setText(_translate("Form", "Teléfono"))
        self.lineEditTelefonoEmpresa.setPlaceholderText(_translate("Form", "Correo"))
        self.label_4.setText(_translate("Form", "Correo"))
        self.lineEditCorreoEmpresa.setPlaceholderText(_translate("Form", "Teléfono"))
        self.btnCancelar.setText(_translate("Form", "Cancelar"))
        self.btnGuardar.setText(_translate("Form", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
