# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/history.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from app.functions.tools.getIcon import getIcon

ResourceIcon = getIcon("Buy.svg")
HistoryIcon = getIcon("History.svg")
InventoryIcon = getIcon("Inventory.svg")
ProviderIcon = getIcon("Providers.svg")

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 707)
        Form.setStyleSheet("#mainWindow {\n"
        "    font-family: Arial;\n"
        "}\n"
        "\n"
        "QLabel {\n"
        "    font-size: 18px;\n"
        "    color: #222;\n"
        "}\n"
        "\n"
        "#labelAdd{\n"
        "    font-size:24px;\n"
        "}\n"
        "\n"
        "#menu {\n"
        "    background: #907c83;\n"
        "    border-bottom: 1.5px solid #bdbdbd;\n"
        "}\n"
        "\n"
        "/* Quitamos las barras laterales de los contenedores */\n"
        "#menu QWidget {\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "/* Aseguramos que los labels (Iconos y Texto) no hereden bordes */\n"
        "#menu QLabel {\n"
        "    font-size: 16px;\n"
        "    color: #222;\n"
        "    border: none;\n"
        "}\n"
        "\n"
        "#menu QWidget:hover {\n"
        "    background: #7f5b5f;\n"
        "}\n"
        "\n"
        "/* Solo la línea inferior se muestra cuando está activo */\n"
        "#menu QWidget[active=\"true\"] {\n"
        "    background: #ffffff;\n"
        "    border-bottom: 3px solid #487c7e;\n"
        "}\n"
        "\n"
        "#menu QWidget[active=\"true\"] QLabel {\n"
        "    font-weight: bold;\n"
        "}\n"
        "\n"
        "QLabel#labelTitulo{\n"
        "    font-size: 36px;\n"
        "    font-weight: 600;\n"
        "    color: #222;\n"
        "}\n"
        "\n"
        "QPushButton#btnAdd {\n"
        "    background: transparent;\n"
        "    font-size: 36px;\n"
        "    color: #222;\n"
        "    border: none;\n"
        "}\n"
        "QPushButton#btnAdd:hover {\n"
        "    color: #444;\n"
        "}\n"
        "\n"
        "QToolButton {\n"
        "    background: transparent;\n"
        "    border: none;\n"
        "}\n"
        "QToolButton:hover {\n"
        "    background: #dcdcdc;\n"
        "    border-radius: 4px;\n"
        "}\n"
        "\n"
        "QPushButton#btnBack {\n"
        "    background: transparent;\n"
        "    border: none;\n"
        "    font-size: 36px;\n"
        "    color: #222;\n"
        "}\n"
        "QPushButton#btnBack:hover {\n"
        "    color: #555;\n"
        "}\n"
        "\n"
        "QTableWidget {\n"
        "    background: #ededed;\n"
        "    gridline-color: transparent;\n"
        "    border-radius: 8px;\n"
        "    font-size: 14px;\n"
        "    color: #222;\n"
        "}\n"
        "\n"
        "QHeaderView::section {\n"
        "    background: #EDEDED;\n"
        "    gridline-color: transparent;\n"

        "    padding: 6px 4px;\n"
        "    font-weight: bold;\n"
        "    border: 1px solid #b4b4b4;\n"
        "}\n"
        "\n"
        "QTableWidget::item {\n"
        "    padding: 6px;\n"
        "}\n"
        "\n"
        "QTableWidget::item:selected {\n"
        "    background: #c6d3d6;\n"
        "    color: #000;\n"
        "}\n"
        "\n"
        "QScrollBar:vertical,\n"
        "QScrollBar:horizontal {\n"
        "    background: #dcdcdc;\n"
        "    border-radius: 4px;\n"
        "}\n"
        "\n"
        "QScrollBar::handle {\n"
        "    background: #aaaaaa;\n"
        "    border-radius: 4px;\n"
        "}\n"
        "QScrollBar::handle:hover {\n"
        "    background: #888888;\n"
        "}\n"
        "\n"
        "#tablaContenedor {\n"
        "    background: #7835ff;\n"
        "    border-radius: 10px;\n"
        "    padding: 8px;\n"
        "}\n"
        "\n"
        "QLineEdit {\n"
        "    background: #DFDFDF;\n"
        "    border-radius: 4px;\n"
        "    padding: 6px;\n"
        "    border: 1px solid #c4c4c4;\n"
        "    font-size: 20px;\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 1px solid #487c7e;\n"
        "}\n"
        "\n"
        "QPushButton#btnComprar {\n"
        "    background: #b9e3a6;\n"
        "    border: none;\n"
        "    border-radius: 6px;\n"
        "    padding: 8px 26px;\n"
        "    font-size: 16px;\n"
        "}\n"
        "\n"
        "QPushButton#btnComprar:hover {\n"
        "    background: #a3d68c;\n"
        "}\n"
        "QToolTip {\n"
"    background-color: #fdfdfd;\n"
"    color: #333333;\n"
"    border: 1px solid #c0c0c0;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    font-size: 12px;\n"
"}\n"
        "")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QWidget(Form)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuItemProveedores = QtWidgets.QWidget(self.menu)
        self.menuItemProveedores.setObjectName("menuItemProveedores")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menuItemProveedores)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMenuProveedores = QtWidgets.QLabel(self.menuItemProveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenuProveedores.sizePolicy().hasHeightForWidth())
        self.labelMenuProveedores.setSizePolicy(sizePolicy)
        self.labelMenuProveedores.setObjectName("labelMenuProveedores")
        self.horizontalLayout_4.addWidget(self.labelMenuProveedores)
        self.labelIconProveedores = QtWidgets.QLabel(self.menuItemProveedores)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIconProveedores.sizePolicy().hasHeightForWidth())
        self.labelIconProveedores.setSizePolicy(sizePolicy)
        self.labelIconProveedores.setMinimumSize(QtCore.QSize(10, 10))
        self.labelIconProveedores.setMaximumSize(QtCore.QSize(25, 25))
        self.labelIconProveedores.setText("")
        self.labelIconProveedores.setPixmap(QtGui.QPixmap(ProviderIcon))
        self.labelIconProveedores.setScaledContents(True)
        self.labelIconProveedores.setObjectName("labelIconProveedores")
        self.horizontalLayout_4.addWidget(self.labelIconProveedores)
        self.horizontalLayout.addWidget(self.menuItemProveedores)
        self.menuItemInventario = QtWidgets.QWidget(self.menu)
        self.menuItemInventario.setObjectName("menuItemInventario")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.menuItemInventario)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelMenuInventario = QtWidgets.QLabel(self.menuItemInventario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenuInventario.sizePolicy().hasHeightForWidth())
        self.labelMenuInventario.setSizePolicy(sizePolicy)
        self.labelMenuInventario.setObjectName("labelMenuInventario")
        self.horizontalLayout_5.addWidget(self.labelMenuInventario)
        self.labelIconInventario = QtWidgets.QLabel(self.menuItemInventario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIconInventario.sizePolicy().hasHeightForWidth())
        self.labelIconInventario.setSizePolicy(sizePolicy)
        self.labelIconInventario.setMinimumSize(QtCore.QSize(0, 0))
        self.labelIconInventario.setMaximumSize(QtCore.QSize(25, 25))
        self.labelIconInventario.setText("")
        self.labelIconInventario.setPixmap(QtGui.QPixmap(InventoryIcon))
        self.labelIconInventario.setScaledContents(True)
        self.labelIconInventario.setObjectName("labelIconInventario")
        self.horizontalLayout_5.addWidget(self.labelIconInventario)
        self.horizontalLayout.addWidget(self.menuItemInventario)
        self.menuItemRecursos = QtWidgets.QWidget(self.menu)
        self.menuItemRecursos.setObjectName("menuItemRecursos")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.menuItemRecursos)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMenuRecursos = QtWidgets.QLabel(self.menuItemRecursos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenuRecursos.sizePolicy().hasHeightForWidth())
        self.labelMenuRecursos.setSizePolicy(sizePolicy)
        self.labelMenuRecursos.setObjectName("labelMenuRecursos")
        self.horizontalLayout_6.addWidget(self.labelMenuRecursos)
        self.labelIconRecursos = QtWidgets.QLabel(self.menuItemRecursos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIconRecursos.sizePolicy().hasHeightForWidth())
        self.labelIconRecursos.setSizePolicy(sizePolicy)
        self.labelIconRecursos.setMinimumSize(QtCore.QSize(0, 0))
        self.labelIconRecursos.setMaximumSize(QtCore.QSize(25, 25))
        self.labelIconRecursos.setText("")
        self.labelIconRecursos.setPixmap(QtGui.QPixmap(ResourceIcon))
        self.labelIconRecursos.setScaledContents(True)
        self.labelIconRecursos.setObjectName("labelIconRecursos")
        self.horizontalLayout_6.addWidget(self.labelIconRecursos)
        self.horizontalLayout.addWidget(self.menuItemRecursos)
        self.menuItemHistorial = QtWidgets.QWidget(self.menu)
        self.menuItemHistorial.setObjectName("menuItemHistorial")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.menuItemHistorial)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelMenuHistorial = QtWidgets.QLabel(self.menuItemHistorial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMenuHistorial.sizePolicy().hasHeightForWidth())
        self.labelMenuHistorial.setSizePolicy(sizePolicy)
        self.labelMenuHistorial.setObjectName("labelMenuHistorial")
        self.horizontalLayout_7.addWidget(self.labelMenuHistorial)
        self.labelIconHistorial = QtWidgets.QLabel(self.menuItemHistorial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIconHistorial.sizePolicy().hasHeightForWidth())
        self.labelIconHistorial.setSizePolicy(sizePolicy)
        self.labelIconHistorial.setMinimumSize(QtCore.QSize(0, 0))
        self.labelIconHistorial.setMaximumSize(QtCore.QSize(25, 25))
        self.labelIconHistorial.setText("")
        self.labelIconHistorial.setPixmap(QtGui.QPixmap(HistoryIcon))
        self.labelIconHistorial.setScaledContents(True)
        self.labelIconHistorial.setObjectName("labelIconHistorial")
        self.horizontalLayout_7.addWidget(self.labelIconHistorial)
        self.horizontalLayout.addWidget(self.menuItemHistorial)
        self.verticalLayout.addWidget(self.menu)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTitulo = QtWidgets.QLabel(Form)
        self.labelTitulo.setObjectName("labelTitulo")
        self.horizontalLayout_2.addWidget(self.labelTitulo)
        self.horizontalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidgetHistorial = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetHistorial.sizePolicy().hasHeightForWidth())
        self.tableWidgetHistorial.setSizePolicy(sizePolicy)
        self.tableWidgetHistorial.setLineWidth(1)
        self.tableWidgetHistorial.setMidLineWidth(1)
        self.tableWidgetHistorial.setWordWrap(True)
        self.tableWidgetHistorial.setObjectName("tableWidgetHistorial")
        self.tableWidgetHistorial.setColumnCount(5)
        self.tableWidgetHistorial.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorial.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorial.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorial.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorial.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistorial.setHorizontalHeaderItem(4, item)
        self.tableWidgetHistorial.horizontalHeader().setVisible(True)
        self.tableWidgetHistorial.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetHistorial.horizontalHeader().setDefaultSectionSize(285)
        self.tableWidgetHistorial.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidgetHistorial)
        self.verticalLayout_2.setStretch(1, 20)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(1, 100)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelMenuProveedores.setText(_translate("Form", "Proveedores"))
        self.labelMenuInventario.setText(_translate("Form", "Inventario"))
        self.labelMenuRecursos.setText(_translate("Form", "Comprar recursos"))
        self.labelMenuHistorial.setText(_translate("Form", "Historial"))
        self.labelTitulo.setText(_translate("Form", "Historial"))
        item = self.tableWidgetHistorial.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Usuario"))
        item = self.tableWidgetHistorial.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Fecha"))
        item = self.tableWidgetHistorial.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Hora"))
        item = self.tableWidgetHistorial.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Total"))
        item = self.tableWidgetHistorial.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ver factura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
