# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/windows/ui/informacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 659)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #f6f5b2;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QLabel#labelTitulo {\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    color: #000;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5a8dee;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#btnRegistrarEnt {\n"
"    background-color: #aee6a4;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#btnRegistrarEnt:hover {\n"
"    background-color: #94d98a;\n"
"}\n"
"\n"
"QPushButton#btnRegistrarSal {\n"
"    background-color: #EEB0B0;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#btnRegistrarSal:hover {\n"
"    background-color: #ee9794;\n"
"}\n"
"\n"
"QPushButton#btnEliminar {\n"
"    background-color: #BAABAB;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#btnEliminar:hover {\n"
"    background-color: #ba9c9a;\n"
"}\n"
"\n"
"\n"
"QPushButton#btnLateral {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton#btnLateral:hover {\n"
"    background-color: #c6c6c6;\n"
"}\n"
"")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLateral = QtWidgets.QPushButton(Form)
        self.btnLateral.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnLateral.setFont(font)
        self.btnLateral.setObjectName("btnLateral")
        self.horizontalLayout.addWidget(self.btnLateral)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitulo = QtWidgets.QLabel(Form)
        self.labelTitulo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setObjectName("labelTitulo")
        self.verticalLayout.addWidget(self.labelTitulo)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelNombre = QtWidgets.QLabel(Form)
        self.labelNombre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelNombre.setFont(font)
        self.labelNombre.setObjectName("labelNombre")
        self.horizontalLayout_6.addWidget(self.labelNombre)
        self.btnEditarNombre = QtWidgets.QLabel(Form)
        self.btnEditarNombre.setMaximumSize(QtCore.QSize(30, 30))
        self.btnEditarNombre.setText("")
        self.btnEditarNombre.setPixmap(QtGui.QPixmap("app/windows/ui/../../assets/icons/Edit.png"))
        self.btnEditarNombre.setScaledContents(True)
        self.btnEditarNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.btnEditarNombre.setWordWrap(False)
        self.btnEditarNombre.setOpenExternalLinks(False)
        self.btnEditarNombre.setObjectName("btnEditarNombre")
        self.horizontalLayout_6.addWidget(self.btnEditarNombre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.textEditNombre = QtWidgets.QTextEdit(Form)
        self.textEditNombre.setObjectName("textEditNombre")
        self.verticalLayout_4.addWidget(self.textEditNombre)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelCodigo = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelCodigo.setFont(font)
        self.labelCodigo.setObjectName("labelCodigo")
        self.verticalLayout_8.addWidget(self.labelCodigo)
        self.textEditFecha = QtWidgets.QTextEdit(Form)
        self.textEditFecha.setObjectName("textEditFecha")
        self.verticalLayout_8.addWidget(self.textEditFecha)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelStock = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelStock.setFont(font)
        self.labelStock.setObjectName("labelStock")
        self.horizontalLayout_4.addWidget(self.labelStock)
        self.btnEditarStock = QtWidgets.QLabel(Form)
        self.btnEditarStock.setMaximumSize(QtCore.QSize(30, 30))
        self.btnEditarStock.setText("")
        self.btnEditarStock.setPixmap(QtGui.QPixmap("app/windows/ui/../../assets/icons/Edit.png"))
        self.btnEditarStock.setScaledContents(True)
        self.btnEditarStock.setObjectName("btnEditarStock")
        self.horizontalLayout_4.addWidget(self.btnEditarStock)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.textEditCliente = QtWidgets.QTextEdit(Form)
        self.textEditCliente.setObjectName("textEditCliente")
        self.verticalLayout_9.addWidget(self.textEditCliente)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelDesc = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelDesc.setFont(font)
        self.labelDesc.setObjectName("labelDesc")
        self.horizontalLayout_7.addWidget(self.labelDesc)
        self.btnEditarDesc = QtWidgets.QLabel(Form)
        self.btnEditarDesc.setMaximumSize(QtCore.QSize(30, 30))
        self.btnEditarDesc.setText("")
        self.btnEditarDesc.setPixmap(QtGui.QPixmap("app/windows/ui/../../assets/icons/Edit.png"))
        self.btnEditarDesc.setScaledContents(True)
        self.btnEditarDesc.setObjectName("btnEditarDesc")
        self.horizontalLayout_7.addWidget(self.btnEditarDesc)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.textEditDesc = QtWidgets.QTextEdit(Form)
        self.textEditDesc.setObjectName("textEditDesc")
        self.verticalLayout_4.addWidget(self.textEditDesc)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(24)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRegistrarEnt = QtWidgets.QPushButton(Form)
        self.btnRegistrarEnt.setObjectName("btnRegistrarEnt")
        self.horizontalLayout_2.addWidget(self.btnRegistrarEnt)
        self.btnRegistrarSal = QtWidgets.QPushButton(Form)
        self.btnRegistrarSal.setObjectName("btnRegistrarSal")
        self.horizontalLayout_2.addWidget(self.btnRegistrarSal)
        self.btnEliminar = QtWidgets.QPushButton(Form)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_2.addWidget(self.btnEliminar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnLateral.setText(_translate("Form", "➔"))
        self.labelTitulo.setText(_translate("Form", "Información"))
        self.labelNombre.setText(_translate("Form", "Nombre"))
        self.labelCodigo.setText(_translate("Form", "Código"))
        self.labelStock.setText(_translate("Form", "Stock"))
        self.labelDesc.setText(_translate("Form", "Descripción"))
        self.btnRegistrarEnt.setText(_translate("Form", "Registrar entrada"))
        self.btnRegistrarSal.setText(_translate("Form", "Registrar salida"))
        self.btnEliminar.setText(_translate("Form", "Eliminar material"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
