# Form implementation generated from reading ui file 'app/windows/ui/loginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys 
import os

if getattr(sys, 'frozen', False):  
    resources_path = sys._MEIPASS 
else:
    resources_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

userIcon = os.path.join(resources_path,"../", "assets", "icons", "User.png")

class Ui_container(object):
    def setupUi(self, container):
        container.setObjectName("container")
        container.resize(1480, 857)
        container.setStyleSheet("#container{\n"
"background-color:\"#FFFFC7\";\n"
"\n"
"}\n"
"#leftSideContainer {\n"
"background-color:\"#548687\";\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"}\n"
"#rightSideContainer {\n"
"background-color:\"#B8B8B8\";\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"}\n"
"\n"
"#passwordField, #cedulaField{\n"
"background-color:\"#fff\";\n"
"color:\"#000\";\n"
"border-radius:3px;\n"
"\n"
"}\n"
"\n"
"#label, #label_2{\n"
"color:\"#000\";\n"
"\n"
"}\n"
"\n"
"#accessButtom{\n"
"background-color:rgb(143, 188, 187);\n"
"border:none;\n"
"    border-radius: 10px;\n"
"}\n"
"#accessButtom:hover{\n"
"background-color:\"#548687\";\n"
"\n"
"}\n"
"")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(container)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftSideContainer = QtWidgets.QFrame(parent=container)
        self.leftSideContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftSideContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftSideContainer.setObjectName("leftSideContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftSideContainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.leftTitle = QtWidgets.QLabel(parent=self.leftSideContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftTitle.sizePolicy().hasHeightForWidth())
        self.leftTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        self.leftTitle.setFont(font)
        self.leftTitle.setLineWidth(1)
        self.leftTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.leftTitle.setObjectName("leftTitle")
        self.verticalLayout_2.addWidget(self.leftTitle)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.leftSideContainer)
        self.rightSideContainer = QtWidgets.QFrame(parent=container)
        self.rightSideContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightSideContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightSideContainer.setObjectName("rightSideContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.rightSideContainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(parent=self.rightSideContainer)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(userIcon))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 6)
        self.horizontalLayout_6.setStretch(2, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, -1, 20, 0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.rightSideContainer)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.cedulaField = QtWidgets.QLineEdit(parent=self.rightSideContainer)
        self.cedulaField.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cedulaField.setFont(font)
        self.cedulaField.setObjectName("cedulaField")
        self.verticalLayout_4.addWidget(self.cedulaField)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.rightSideContainer)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.passwordField = QtWidgets.QLineEdit(parent=self.rightSideContainer)
        self.passwordField.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.passwordField.setFont(font)
        self.passwordField.setObjectName("passwordField")
        self.verticalLayout_5.addWidget(self.passwordField)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 5)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.accessButtom = QtWidgets.QPushButton(parent=self.rightSideContainer)
        self.accessButtom.setMinimumSize(QtCore.QSize(0, 50))
        self.accessButtom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.accessButtom.setObjectName("accessButtom")
        self.verticalLayout_6.addWidget(self.accessButtom)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.verticalLayout_6.setStretch(0, 3)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 3)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(2, 5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 6)
        self.horizontalLayout_5.setStretch(2, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.rightSideContainer)
        self.horizontalLayout_2.setStretch(0, 53)
        self.horizontalLayout_2.setStretch(1, 47)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 8)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 70)
        self.horizontalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(container)
        QtCore.QMetaObject.connectSlotsByName(container)

    def retranslateUi(self, container):
        _translate = QtCore.QCoreApplication.translate
        container.setWindowTitle(_translate("container", "Form"))
        self.leftTitle.setText(_translate("container", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Bienvenido al</span></p><p><span style=\" font-size:14pt; font-weight:600;\"><br/>Sistema de Gestión de Inventario</span></p></body></html>"))
        self.label.setText(_translate("container", "Cédula"))
        self.label_2.setText(_translate("container", "Contraseña"))
        self.accessButtom.setText(_translate("container", "Ingresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    container = QtWidgets.QWidget()
    ui = Ui_container()
    ui.setupUi(container)
    container.show()
    sys.exit(app.exec())
