# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/newPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from app.functions.tools.getIcon import getIcon

from PyQt5 import QtCore, QtGui, QtWidgets

LogoIcon = getIcon("Logo.png")
CodeIcon = getIcon("Codigo.svg")

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(994, 710)
        Form.setStyleSheet("QWidget {\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"#login {\n"
"    background: #F0F6F9;\n"
"}\n"
"\n"
"\n"
"#panelIzquierdo {\n"
"    background: #487c7e;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#labelTitulo {\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#panelDerecho{\n"
"    background: #d1d2d4;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #487c7e;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #333;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"#labelLink{\n"
"    color: #4054d6;\n"
"    font-size: 13px;\n"
"}\n"
"#labelLink:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: #dedede;\n"
"    color: #333;\n"
"    border-radius: 6px;\n"
"    padding: 7px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #cacaca;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #b5b5b5;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panelIzquierdo = QtWidgets.QWidget(Form)
        self.panelIzquierdo.setObjectName("panelIzquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panelIzquierdo)
        self.verticalLayout_2.setContentsMargins(20, 20, 50, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLogo = QtWidgets.QLabel(self.panelIzquierdo)
        self.labelLogo.setMaximumSize(QtCore.QSize(200, 200))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(LogoIcon))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_2.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelTitulo = QtWidgets.QLabel(self.panelIzquierdo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitulo.sizePolicy().hasHeightForWidth())
        self.labelTitulo.setSizePolicy(sizePolicy)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.verticalLayout_2.addWidget(self.labelTitulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 3)
        self.horizontalLayout.addWidget(self.panelIzquierdo)
        self.panelDerecho = QtWidgets.QWidget(Form)
        self.panelDerecho.setObjectName("panelDerecho")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panelDerecho)
        self.verticalLayout.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.labelIconUser = QtWidgets.QLabel(self.panelDerecho)
        self.labelIconUser.setMaximumSize(QtCore.QSize(100, 100))
        self.labelIconUser.setText("")
        self.labelIconUser.setTextFormat(QtCore.Qt.AutoText)
        self.labelIconUser.setPixmap(QtGui.QPixmap(CodeIcon))
        self.labelIconUser.setScaledContents(True)
        self.labelIconUser.setObjectName("labelIconUser")
        self.verticalLayout.addWidget(self.labelIconUser, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelCodigo = QtWidgets.QLabel(self.panelDerecho)
        self.labelCodigo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCodigo.setObjectName("labelCodigo")
        self.verticalLayout_4.addWidget(self.labelCodigo)
        self.lineEditPasscode = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPasscode.sizePolicy().hasHeightForWidth())
        self.lineEditPasscode.setSizePolicy(sizePolicy)
        self.lineEditPasscode.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditPasscode.setBaseSize(QtCore.QSize(0, -3968))
        self.lineEditPasscode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditPasscode.setObjectName("lineEditPasscode")
        self.verticalLayout_4.addWidget(self.lineEditPasscode)
        self.label = QtWidgets.QLabel(self.panelDerecho)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.lineEditConfirmar = QtWidgets.QLineEdit(self.panelDerecho)
        self.lineEditConfirmar.setObjectName("lineEditConfirmar")
        self.verticalLayout_4.addWidget(self.lineEditConfirmar)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonAceptar = QtWidgets.QPushButton(self.panelDerecho)
        self.buttonAceptar.setMinimumSize(QtCore.QSize(250, 0))
        self.buttonAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonAceptar.setObjectName("buttonAceptar")
        self.verticalLayout_3.addWidget(self.buttonAceptar, 0, QtCore.Qt.AlignHCenter)
        self.buttonVolver = QtWidgets.QPushButton(self.panelDerecho)
        self.buttonVolver.setMinimumSize(QtCore.QSize(250, 0))
        self.buttonVolver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonVolver.setObjectName("buttonVolver")
        self.verticalLayout_3.addWidget(self.buttonVolver, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.panelDerecho)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitulo.setText(_translate("Form", "<html><head/><body><p>Bienvenido</p><p>al sistema PROCURA</p></body></html>"))
        self.labelCodigo.setText(_translate("Form", "Nueva contraseña"))
        self.label.setText(_translate("Form", "Confirme su contraseña"))
        self.buttonAceptar.setText(_translate("Form", "Aceptar"))
        self.buttonVolver.setText(_translate("Form", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
