# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/providersRegistrationProducts.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1385, 963)
        Form.setStyleSheet("""
    #mainWindow {
        font-family: Arial;
    }
    QLabel {
        font-size: 18px;
        color: #222;
    }
    QLineEdit {
        background: white;
        border-radius: 4px;
        padding: 6px;
        border: 1px solid #c4c4c4;
        font-size: 20px;
    }
    QLineEdit:focus {
        border: 1px solid #487c7e;
    }
    QLabel#labelTituloProveedores {
        font-size: 36px;
        font-weight: 600;
        color: #222;
        padding: 10px 0;
    }
    QPushButton#btnCancelar {
        background: #e7b0b0;
        border: none;
        border-radius: 6px;
        padding: 12px 40px;
        font-size: 18px;
        font-weight: bold;
    }
    QPushButton#btnCancelar:hover {
        background: #d59a9a;
    }
    QPushButton#btnGuardar {
        background: #b9e3a6;
        border: none;
        border-radius: 6px;
        padding: 12px 40px;
        font-size: 18px;
        font-weight: bold;
    }
    QPushButton#btnGuardar:hover {
        background: #a3d68c;
    }
    QPushButton#btnAddProducto {
        font-size: 16px;
        font-weight: bold;
        padding: 10px 20px;
        background: #487c7e;
        color: white;
        border: none;
        border-radius: 6px;
    }
    QPushButton#btnAddProducto:hover {
        background: #3a6365;
    }
    #panelRegistro {
        background: #eee;
        border: none;
        padding: 20px;
    }
    
    QTableWidget {
        background: #eee;
        gridline-color: transparent;
        font-size: 14px;
        color: #222;
        border: none;
        outline: none;
        alternate-background-color: #eee; /* Para filas alternas */
    }
    verticalLayout_4{
        background: #eee;
        border: none;
    }
    QHeaderView::section {
        background: #eee;
        gridline-color: transparent;
        border: none;
        padding: 8px;
        font-weight: bold;
        font-size: 14px;
        color: #222;
    }
    
    QHeaderView::section:checked {
        background: #ddd;
    }
    
    QTableCornerButton::section {
        background: #eee;
        border: none;
    }
    
    QTableWidget::item {
        padding: 6px;
        border: none;
        border-bottom: 1px solid #ddd;
    }
    
    QTableWidget::item:selected {
        background: #c6d3d6;
        color: #000;
    }
    
    QTableWidget QScrollBar:vertical {
        background: #f1f3f5;
        border-radius: 4px;
        width: 12px;
        margin: 0px;
        border: none;
    }
    
    QTableWidget QScrollBar::handle:vertical {
        background: #adb5bd;
        border-radius: 4px;
        min-height: 30px;
        border: none;
    }
    
    QTableWidget QScrollBar::handle:vertical:hover {
        background: #868e96;
    }
    
    QTableWidget QScrollBar:horizontal {
        background: #f1f3f5;
        border-radius: 4px;
        height: 12px;
        margin: 0px;
        border: none;
    }
    
    QTableWidget QScrollBar::handle:horizontal {
        background: #adb5bd;
        border-radius: 4px;
        min-width: 30px;
        border: none;
    }
    
    QTableWidget QScrollBar::handle:horizontal:hover {
        background: #868e96;
    }
    
    /* Estilo para el botón de eliminar en las celdas */
    QTableWidget QPushButton {
        font-weight: bold;
        font-size: 12px;
        color: white;
        background-color: #ff6b6b;
        border-radius: 4px;
        padding: 4px 8px;
        border: none;
    }
    
    QTableWidget QPushButton:hover {
        background-color: #ff5252;
    }
    /* ================================================= */
    
    /* Estilos adicionales para la distribución 5%-90%-5% */
    QLabel#labelDatos {
        font-size: 20px;
        font-weight: bold;
        color: #000;
        padding: 10px;
        background: #eee;
        border-radius: 6px;
        margin-bottom: 10px;
    }
""")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        
        # MÁRGENES COMO EN providers.ui
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)  # Márgenes iguales
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        # Título
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTituloProveedores = QtWidgets.QLabel(Form)
        self.labelTituloProveedores.setObjectName("labelTituloProveedores")
        self.horizontalLayout_2.addWidget(self.labelTituloProveedores)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        
        # QUITAR el spacer extra que tenías aquí
        # spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem)
        
        # Panel principal - SIMPLIFICAR
        self.panelRegistro = QtWidgets.QWidget(Form)
        self.panelRegistro.setObjectName("panelRegistro")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panelRegistro)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        # Título de productos
        self.labelDatos = QtWidgets.QLabel(self.panelRegistro)
        self.labelDatos.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelDatos.setFont(font)
        self.labelDatos.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDatos.setObjectName("labelDatos")
        self.verticalLayout_4.addWidget(self.labelDatos)
        
        # Tabla de productos - CONFIGURAR IGUAL QUE EN providers.ui
        self.tableWidget = QtWidgets.QTableWidget(self.panelRegistro)
        
        # IMPORTANTE: Añadir esta configuración de tamaño
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        
        # Configurar encabezados
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        
        # Configuración del header como en providers.ui
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)  # Tamaño por defecto
        self.tableWidget.horizontalHeader().setStretchLastSection(True)  # Última sección se estira
        
        self.verticalLayout_4.addWidget(self.tableWidget)
        
        # Layout horizontal para el botón "Agregar Producto"
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        
        # Espaciador a la izquierda para empujar el botón a la derecha
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        
        # Botón "Agregar Producto"
        self.btnAddProducto = QtWidgets.QPushButton(self.panelRegistro)
        self.btnAddProducto.setObjectName("btnAddProducto")
        self.btnAddProducto.setText("+ Agregar Producto")
        self.horizontalLayout_6.addWidget(self.btnAddProducto)
        
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        
        self.verticalLayout_2.addWidget(self.panelRegistro)
        
        # Botones inferiores
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(250, -1, 250, 0)
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.btnCancelar = QtWidgets.QPushButton(Form)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        
        self.btnGuardar = QtWidgets.QPushButton(Form)
        self.btnGuardar.setObjectName("btnGuardar")
        self.horizontalLayout_5.addWidget(self.btnGuardar)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        # CONFIGURACIÓN DE STRETCH - ESTO VA DESPUÉS DE AGREGAR TODO
        # Título: 5%, Tabla: 90%, Botones: 5%
        self.verticalLayout_4.setStretch(0, 10)    # Título (5%)
        self.verticalLayout_4.setStretch(1, 80)   # Panel con tabla (90%)
        self.verticalLayout_4.setStretch(2, 10)    # Botones (5%)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Registro de proveedores"))
        self.labelTituloProveedores.setText(_translate("Form", "Registro de proveedores"))
        self.labelDatos.setText(_translate("Form", "Pedidos"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Descripción"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Existencia"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Stock Mínimo"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Eliminar"))
        
        self.btnCancelar.setText(_translate("Form", "Cancelar"))
        self.btnGuardar.setText(_translate("Form", "Guardar Productos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.showMaximized()
    sys.exit(app.exec_())