# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/providersRegistration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 694)
        Form.setStyleSheet("#mainWindow {\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#labelAdd{\n"
"    font-size:24px;\n"
"}\n"
"\n"
"#menu {\n"
"    background: #907c83;\n"
"    border-bottom: 1.5px solid #bdbdbd;\n"
"}\n"
"\n"
"#menu QLabel {\n"
"    font-size: 16px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#menu QWidget:hover {\n"
"    background: #e0e0e0;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] {\n"
"    background: #ffffff;\n"
"    border-bottom: 3px solid #487c7e;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] QLabel {\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#menu QWidget {\n"
"    border-right: 1px solid #bdbdbd;\n"
"    border-left: 1px solid #bdbdbd;\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #487c7e;\n"
"}\n"
"\n"
"QLabel#labelTituloProveedores{\n"
"    font-size: 36px;\n"
"    font-weight: 600;\n"
"    color: #222;\n"
"}\n"
"\n"
"QPushButton#btnAdd {\n"
"    background: transparent;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"    border: none;\n"
"}\n"
"QPushButton#btnAdd:hover {\n"
"    color: #444;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QToolButton:hover {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#btnBack {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"}\n"
"QPushButton#btnBack:hover {\n"
"    color: #555;\n"
"}\n"
"\n"
"\n"
"QTableWidget {\n"
"    background: #EAEB8C;\n"
"    gridline-color: #bcbcbc;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    color: #222;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #EBEC8D;\n"
"    padding: 6px 4px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #b4b4b4;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: #c6d3d6;\n"
"    color: #000;\n"
"}\n"
"\n"
"QScrollBar:vertical,\n"
"QScrollBar:horizontal {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #aaaaaa;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    background: #888888;\n"
"}\n"
"\n"
"#tablaContenedor {\n"
"    background: #7835ff;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto,\n"
"QPushButton#btnRemoveProducto {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto:hover,\n"
"QPushButton#btnRemoveProducto:hover {\n"
"    color: #487c7e;\n"
"}\n"
"\n"
"QPushButton#btnCancelar {\n"
"    background: #e7b0b0;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnCancelar:hover {\n"
"    background: #d59a9a;\n"
"}\n"
"\n"
"QPushButton#btnGuardar {\n"
"    background: #b9e3a6;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnGuardar:hover {\n"
"    background: #a3d68c;\n"
"}\n"
"\n"
"#panelRegistro {\n"
"    background: #e0e0e0;\n"
"    border-radius: 8px;\n"
"    border: 1.5px solid #b8b8b8;\n"
"    padding: 16px;\n"
"}\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTituloProveedores = QtWidgets.QLabel(Form)
        self.labelTituloProveedores.setObjectName("labelTituloProveedores")
        self.horizontalLayout_2.addWidget(self.labelTituloProveedores)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.panelRegistro = QtWidgets.QWidget(Form)
        self.panelRegistro.setObjectName("panelRegistro")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panelRegistro)
        self.horizontalLayout_4.setSpacing(45)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.labelDatos = QtWidgets.QLabel(self.panelRegistro)
        self.labelDatos.setAlignment(QtCore.Qt.AlignCenter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDatos.sizePolicy().hasHeightForWidth())
        self.labelDatos.setSizePolicy(sizePolicy)
        self.labelDatos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelDatos.setObjectName("labelDatos")
        self.verticalLayout_4.addWidget(self.labelDatos)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(36)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEditNameEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNameEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditNameEmpresa.setSizePolicy(sizePolicy)
        self.lineEditNameEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditNameEmpresa.setObjectName("lineEditNameEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditNameEmpresa)
        self.lineEditDireccionEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDireccionEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditDireccionEmpresa.setSizePolicy(sizePolicy)
        self.lineEditDireccionEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditDireccionEmpresa.setObjectName("lineEditDireccionEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditDireccionEmpresa)
        self.lineEditCorreoEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCorreoEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditCorreoEmpresa.setSizePolicy(sizePolicy)
        self.lineEditCorreoEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditCorreoEmpresa.setObjectName("lineEditCorreoEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditCorreoEmpresa)
        self.lineEditTelefonoEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTelefonoEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditTelefonoEmpresa.setSizePolicy(sizePolicy)
        self.lineEditTelefonoEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditTelefonoEmpresa.setObjectName("lineEditTelefonoEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditTelefonoEmpresa)
        self.lineEditRIFEmpresa = QtWidgets.QLineEdit(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRIFEmpresa.sizePolicy().hasHeightForWidth())
        self.lineEditRIFEmpresa.setSizePolicy(sizePolicy)
        self.lineEditRIFEmpresa.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEditRIFEmpresa.setObjectName("lineEditRIFEmpresa")
        self.verticalLayout_5.addWidget(self.lineEditRIFEmpresa)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.verticalLayout_5.setStretch(4, 100)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(3, 100)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.labelProductos = QtWidgets.QLabel(self.panelRegistro)
        self.labelProductos.setObjectName("labelProductos")
        self.verticalLayout_3.addWidget(self.labelProductos)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableProducto = QtWidgets.QTableWidget(self.panelRegistro)
        self.tableProducto.setMinimumSize(QtCore.QSize(0, 350))
        self.tableProducto.setObjectName("tableProducto")
        self.tableProducto.setColumnCount(4)
        self.tableProducto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(3, item)
        self.tableProducto.horizontalHeader().setDefaultSectionSize(125)
        self.tableProducto.horizontalHeader().setMinimumSectionSize(50)
        self.tableProducto.horizontalHeader().setStretchLastSection(True)
        self.tableProducto.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_6.addWidget(self.tableProducto)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 100)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.panelRegistro)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(250, 1, 250, 0)
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnCancelar = QtWidgets.QPushButton(Form)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        self.btnGuardar = QtWidgets.QPushButton(Form)
        self.btnGuardar.setObjectName("btnGuardar")
        self.horizontalLayout_5.addWidget(self.btnGuardar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 10)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTituloProveedores.setText(_translate("Form", "Registrar Proveedor"))
        self.labelDatos.setText(_translate("Form", "Datos de la empresa"))
        self.lineEditNameEmpresa.setPlaceholderText(_translate("Form", "Nombre de la empresa"))
        self.lineEditDireccionEmpresa.setPlaceholderText(_translate("Form", "Dirección de la empresa"))
        self.lineEditCorreoEmpresa.setPlaceholderText(_translate("Form", "Correo"))
        self.lineEditTelefonoEmpresa.setPlaceholderText(_translate("Form", "Teléfono"))
        self.lineEditRIFEmpresa.setPlaceholderText(_translate("Form", "RIF"))
        self.labelProductos.setText(_translate("Form", "Productos"))
        item = self.tableProducto.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Producto"))
        item = self.tableProducto.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stock"))
        item = self.tableProducto.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Precio unitario"))
        item = self.tableProducto.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Borrar"))
        self.btnCancelar.setText(_translate("Form", "Cancelar"))
        self.btnGuardar.setText(_translate("Form", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
