# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/purchase.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 694)
        Form.setStyleSheet("#mainWindow {\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#labelAdd{\n"
"    font-size:24px;\n"
"}\n"
"\n"
"#menu {\n"
"    background: #D9D9D9;\n"
"    border-bottom: 1.5px solid #bdbdbd;\n"
"}\n"
"\n"
"#menu QLabel {\n"
"    font-size: 16px;\n"
"    color: #222;\n"
"}\n"
"\n"
"#menu QWidget:hover {\n"
"    background: #e0e0e0;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] {\n"
"    background: #ffffff;\n"
"    border-bottom: 3px solid #487c7e;\n"
"}\n"
"\n"
"#menu QWidget[active=\"true\"] QLabel {\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#menu QWidget {\n"
"    border-right: 1px solid #bdbdbd;\n"
"    border-left: 1px solid #bdbdbd;\n"
"\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #487c7e;\n"
"}\n"
"\n"
"QLabel#labelTitulo{\n"
"    font-size: 36px;\n"
"    font-weight: 600;\n"
"    color: #222;\n"
"}\n"
"\n"
"QPushButton#btnAdd {\n"
"    background: transparent;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"    border: none;\n"
"}\n"
"QPushButton#btnAdd:hover {\n"
"    color: #444;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QToolButton:hover {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton#btnBack {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 36px;\n"
"    color: #222;\n"
"}\n"
"QPushButton#btnBack:hover {\n"
"    color: #555;\n"
"}\n"
"\n"
"\n"
"QTableWidget {\n"
"    background: #D9D9D9;\n"
"    gridline-color: #bcbcbc;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    color: #222;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #d0d0d0;\n"
"    padding: 6px 4px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #b4b4b4;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: #c6d3d6;\n"
"    color: #000;\n"
"}\n"
"\n"
"QScrollBar:vertical,\n"
"QScrollBar:horizontal {\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #aaaaaa;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:hover {\n"
"    background: #888888;\n"
"}\n"
"\n"
"#tablaContenedor {\n"
"    background: #7835ff;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto,\n"
"QPushButton#btnRemoveProducto {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#btnAddProducto:hover,\n"
"QPushButton#btnRemoveProducto:hover {\n"
"    color: #487c7e;\n"
"}\n"
"\n"
"QPushButton#btnCancelar {\n"
"    background: #e7b0b0;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnCancelar:hover {\n"
"    background: #d59a9a;\n"
"}\n"
"\n"
"QPushButton#btnGuardar {\n"
"    background: #b9e3a6;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 26px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#btnGuardar:hover {\n"
"    background: #a3d68c;\n"
"}\n"
"\n"
"#panelRegistro {\n"
"    background: #e0e0e0;\n"
"    border-radius: 8px;\n"
"    border: 1.5px solid #b8b8b8;\n"
"    padding: 16px;\n"
"}\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelTitulo = QtWidgets.QLabel(Form)
        self.labelTitulo.setObjectName("labelTitulo")
        self.verticalLayout_4.addWidget(self.labelTitulo)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.panelRegistro = QtWidgets.QWidget(Form)
        self.panelRegistro.setObjectName("panelRegistro")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panelRegistro)
        self.horizontalLayout_4.setSpacing(45)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableProducto = QtWidgets.QTableWidget(self.panelRegistro)
        self.tableProducto.setMinimumSize(QtCore.QSize(0, 350))
        self.tableProducto.setObjectName("tableProducto")
        self.tableProducto.setColumnCount(5)
        self.tableProducto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducto.setHorizontalHeaderItem(4, item)
        self.tableProducto.horizontalHeader().setDefaultSectionSize(200)
        self.tableProducto.horizontalHeader().setMinimumSectionSize(50)
        self.tableProducto.horizontalHeader().setStretchLastSection(True)
        self.tableProducto.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_6.addWidget(self.tableProducto)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tableWidget = QtWidgets.QTableWidget(self.panelRegistro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 65))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.panelRegistro)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(250, -1, 250, 0)
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnCancelar = QtWidgets.QPushButton(Form)
        self.btnCancelar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_5.addWidget(self.btnCancelar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 10)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitulo.setText(_translate("Form", "Factura"))
        self.label_2.setText(_translate("Form", "**-**-** / **:** "))
        item = self.tableProducto.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Proveedor"))
        item = self.tableProducto.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Producto"))
        item = self.tableProducto.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cantidad"))
        item = self.tableProducto.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Precio unitario"))
        item = self.tableProducto.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Subtotal"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Total"))
        self.label.setText(_translate("Form", "Compra realizada por:"))
        self.btnCancelar.setText(_translate("Form", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
