# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './app/windows/ui/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from app.functions.tools.getIcon import getIcon

LogoIcon = getIcon("Logo.png")

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(999, 710)
        Form.setStyleSheet("QWidget {\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"#login {\n"
"    background: #F0F6F9;\n"
"}\n"
"\n"
"\n"
"#panelIzquierdo {\n"
"    background: #487c7e;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#labelTitulo {\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#labelTituloRegistro {\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#panelDerecho{\n"
"    background: #d1d2d4;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    border: 1px solid #c4c4c4;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #487c7e;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #333;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#labelLink{\n"
"    color: #4054d6;\n"
"    font-size: 13px;\n"
"}\n"
"#labelLink:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: #dedede;\n"
"    color: #333;\n"
"    border-radius: 6px;\n"
"    padding: 7px;\n"
"    border: none;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #cacaca;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #b5b5b5;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panelIzquierdo = QtWidgets.QWidget(Form)
        self.panelIzquierdo.setObjectName("panelIzquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panelIzquierdo)
        self.verticalLayout_2.setContentsMargins(20, 20, 50, 40)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLogo = QtWidgets.QLabel(self.panelIzquierdo)
        self.labelLogo.setMaximumSize(QtCore.QSize(200, 200))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(LogoIcon))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.verticalLayout_2.addWidget(self.labelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.labelTitulo = QtWidgets.QLabel(self.panelIzquierdo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitulo.sizePolicy().hasHeightForWidth())
        self.labelTitulo.setSizePolicy(sizePolicy)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.verticalLayout_2.addWidget(self.labelTitulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.setStretch(3, 3)
        self.horizontalLayout.addWidget(self.panelIzquierdo)
        self.panelDerecho = QtWidgets.QWidget(Form)
        self.panelDerecho.setObjectName("panelDerecho")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panelDerecho)
        self.verticalLayout.setContentsMargins(50, 100, 50, 40)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.labelTituloRegistro = QtWidgets.QLabel(self.panelDerecho)
        self.labelTituloRegistro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistro.setObjectName("labelTituloRegistro")
        self.verticalLayout.addWidget(self.labelTituloRegistro, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(24)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEditCedula = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCedula.sizePolicy().hasHeightForWidth())
        self.lineEditCedula.setSizePolicy(sizePolicy)
        self.lineEditCedula.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditCedula.setBaseSize(QtCore.QSize(0, -3968))
        self.lineEditCedula.setText("")
        self.lineEditCedula.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditCedula.setObjectName("lineEditCedula")
        self.verticalLayout_4.addWidget(self.lineEditCedula)
        self.lineEditNombre = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNombre.sizePolicy().hasHeightForWidth())
        self.lineEditNombre.setSizePolicy(sizePolicy)
        self.lineEditNombre.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditNombre.setBaseSize(QtCore.QSize(0, -3968))
        self.lineEditNombre.setText("")
        self.lineEditNombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditNombre.setObjectName("lineEditNombre")
        self.verticalLayout_4.addWidget(self.lineEditNombre)
        self.lineEditApellido = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditApellido.sizePolicy().hasHeightForWidth())
        self.lineEditApellido.setSizePolicy(sizePolicy)
        self.lineEditApellido.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditApellido.setBaseSize(QtCore.QSize(0, -3968))
        self.lineEditApellido.setText("")
        self.lineEditApellido.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditApellido.setObjectName("lineEditApellido")
        self.verticalLayout_4.addWidget(self.lineEditApellido)
        self.lineEditCorreo = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCorreo.sizePolicy().hasHeightForWidth())
        self.lineEditCorreo.setSizePolicy(sizePolicy)
        self.lineEditCorreo.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditCorreo.setText("")
        self.lineEditCorreo.setObjectName("lineEditCorreo")
        self.verticalLayout_4.addWidget(self.lineEditCorreo)
        self.lineEditPass = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPass.sizePolicy().hasHeightForWidth())
        self.lineEditPass.setSizePolicy(sizePolicy)
        self.lineEditPass.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditPass.setText("")
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPass.setObjectName("lineEditPass")
        self.verticalLayout_4.addWidget(self.lineEditPass)
        self.lineEditPass_2 = QtWidgets.QLineEdit(self.panelDerecho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPass_2.sizePolicy().hasHeightForWidth())
        self.lineEditPass_2.setSizePolicy(sizePolicy)
        self.lineEditPass_2.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEditPass_2.setText("")
        self.lineEditPass_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPass_2.setObjectName("lineEditPass_2")
        self.verticalLayout_4.addWidget(self.lineEditPass_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonCrear = QtWidgets.QPushButton(self.panelDerecho)
        self.buttonCrear.setMinimumSize(QtCore.QSize(250, 0))
        self.buttonCrear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCrear.setObjectName("buttonCrear")
        self.verticalLayout_3.addWidget(self.buttonCrear, 0, QtCore.Qt.AlignHCenter)
        self.buttonCancelar = QtWidgets.QPushButton(self.panelDerecho)
        self.buttonCancelar.setMinimumSize(QtCore.QSize(250, 0))
        self.buttonCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCancelar.setObjectName("buttonCancelar")
        self.verticalLayout_3.addWidget(self.buttonCancelar, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout.addWidget(self.panelDerecho)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitulo.setText(_translate("Form", "<html><head/><body><p>Bienvenido</p><p>al sistema PROCURA</p></body></html>"))
        self.labelTituloRegistro.setText(_translate("Form", "<html><head/><body><p>Registro de usuario</p></body></html>"))
        self.lineEditCedula.setPlaceholderText(_translate("Form", "Cédula"))
        self.lineEditNombre.setPlaceholderText(_translate("Form", "Primer Nombre"))
        self.lineEditApellido.setPlaceholderText(_translate("Form", "Primer Apellido"))
        self.lineEditCorreo.setPlaceholderText(_translate("Form", "Correo"))
        self.lineEditPass.setPlaceholderText(_translate("Form", "Contraseña"))
        self.lineEditPass_2.setPlaceholderText(_translate("Form", "Confirmar Contraseña"))
        self.buttonCrear.setText(_translate("Form", "Crear usuario"))
        self.buttonCancelar.setText(_translate("Form", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
