from PyQt5 import QtCore, QtGui, QtWidgets

from app.functions.tools.getIcon import getIcon

BoxIcon = getIcon("Box.png")
ClockIcon = getIcon("Clock.png")
ComputerIcon = getIcon("PersonalComputer.png")
PlusIcon = getIcon("Plus.png")
StadisticIcon = getIcon("Stadistic.png")

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(432, 628)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #DDDDDD;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QLabel#labelTitulo {\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    color: #000;\n"
"    padding: 4px;\n"
"}\n"
"QLabel[clickable=\"true\"]:hover {\n"
"    background-color: #CCCCCC;\n"
"    cursor: pointer;\n"
"}"
)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(ComputerIcon))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, -1, 0, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconInventario = QtWidgets.QLabel(Form)
        self.iconInventario.setMaximumSize(QtCore.QSize(40, 40))
        self.iconInventario.setText("")
        self.iconInventario.setPixmap(QtGui.QPixmap(BoxIcon))
        self.iconInventario.setScaledContents(True)
        self.iconInventario.setObjectName("iconInventario")
        self.horizontalLayout.addWidget(self.iconInventario)
        self.labelInventario = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelInventario.setFont(font)
        self.labelInventario.setObjectName("labelInventario")
        self.horizontalLayout.addWidget(self.labelInventario)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconNuevo = QtWidgets.QLabel(Form)
        self.iconNuevo.setMaximumSize(QtCore.QSize(40, 40))
        self.iconNuevo.setText("")
        self.iconNuevo.setPixmap(QtGui.QPixmap(PlusIcon))
        self.iconNuevo.setScaledContents(True)
        self.iconNuevo.setObjectName("iconNuevo")
        self.horizontalLayout_2.addWidget(self.iconNuevo)
        self.labelNuevo = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelNuevo.setFont(font)
        self.labelNuevo.setObjectName("labelNuevo")
        self.horizontalLayout_2.addWidget(self.labelNuevo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconHistorial = QtWidgets.QLabel(Form)
        self.iconHistorial.setMaximumSize(QtCore.QSize(40, 40))
        self.iconHistorial.setText("")
        self.iconHistorial.setPixmap(QtGui.QPixmap(ClockIcon))
        self.iconHistorial.setScaledContents(True)
        self.iconHistorial.setObjectName("iconHistorial")
        self.horizontalLayout_4.addWidget(self.iconHistorial)
        self.labelHistorial = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelHistorial.setFont(font)
        self.labelHistorial.setObjectName("labelHistorial")
        self.horizontalLayout_4.addWidget(self.labelHistorial)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.iconEstadistica = QtWidgets.QLabel(Form)
        self.iconEstadistica.setMaximumSize(QtCore.QSize(40, 40))
        self.iconEstadistica.setText("")
        self.iconEstadistica.setPixmap(QtGui.QPixmap(StadisticIcon))
        self.iconEstadistica.setScaledContents(True)
        self.iconEstadistica.setObjectName("iconEstadistica")
        self.horizontalLayout_5.addWidget(self.iconEstadistica)
        self.labelEstadistica = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelEstadistica.setFont(font)
        self.labelEstadistica.setObjectName("labelEstadistica")
        self.horizontalLayout_5.addWidget(self.labelEstadistica)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Sistema de Inventario"))
        self.labelInventario.setText(_translate("Form", "Inventario"))
        self.labelNuevo.setText(_translate("Form", "Nuevo producto"))
        self.labelHistorial.setText(_translate("Form", "Historial"))
        self.labelEstadistica.setText(_translate("Form", "Estadísticas"))
        self.label_13.setText(_translate("Form", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
