# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/windows/ui/stadisticsEntradaSalida.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 659)
        Form.setStyleSheet("#labelHoy{\n"
"color:\"#528283\";\n"
"}\n"
"QWidget {\n"
"    background-color: #f6f5b2;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QLabel#labelTitulo {\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    color: #000;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5a8dee;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#entradasysalidasBtn{\n"
"    background-color: #aee6a4;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton#materialesBtn {\n"
"    background-color: #ddd;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#entradasysalidasBtn:hover {\n"
"    background-color: #94d98a;\n"
"}\n"
"\n"
"QPushButton#btnRegistrarSal {\n"
"    background-color: #EEB0B0;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#btnRegistrarSal:hover {\n"
"    background-color: #ee9794;\n"
"}\n"
"\n"
"QPushButton#btnEliminar {\n"
"    background-color: #BAABAB;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"}\n"
"QPushButton#btnEliminar:hover {\n"
"    background-color: #ba9c9a;\n"
"}\n"
"\n"
"\n"
"QPushButton#btnLateral {\n"
"    background-color: #dcdcdc;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"}\n"
"QPushButton#btnLateral:hover {\n"
"    background-color: #c6c6c6;\n"
"}\n"
"")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLateral = QtWidgets.QPushButton(Form)
        self.btnLateral.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnLateral.setFont(font)
        self.btnLateral.setObjectName("btnLateral")
        self.horizontalLayout.addWidget(self.btnLateral)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelTitulo = QtWidgets.QLabel(Form)
        self.labelTitulo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setObjectName("labelTitulo")
        self.horizontalLayout_2.addWidget(self.labelTitulo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(70)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.materialesBtn = QtWidgets.QPushButton(Form)
        self.materialesBtn.setObjectName("materialesBtn")
        self.horizontalLayout_3.addWidget(self.materialesBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.entradasysalidasBtn = QtWidgets.QPushButton(Form)
        self.entradasysalidasBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.entradasysalidasBtn.setObjectName("entradasysalidasBtn")
        self.horizontalLayout_3.addWidget(self.entradasysalidasBtn)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 4)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 60)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelSiempre = QtWidgets.QLabel(Form)
        self.labelSiempre.setObjectName("labelSiempre")
        self.verticalLayout_6.addWidget(self.labelSiempre)
        self.label30Dias = QtWidgets.QLabel(Form)
        self.label30Dias.setObjectName("label30Dias")
        self.verticalLayout_6.addWidget(self.label30Dias)
        self.labelHoy = QtWidgets.QLabel(Form)
        self.labelHoy.setObjectName("labelHoy")
        self.verticalLayout_6.addWidget(self.labelHoy)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setStyleSheet("border:none;")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("border:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnLateral.setText(_translate("Form", "➔"))
        self.labelTitulo.setText(_translate("Form", "Estadísticas"))
        self.materialesBtn.setText(_translate("Form", "Materiales"))
        self.entradasysalidasBtn.setText(_translate("Form", "Entradas y Salidas"))
        self.labelSiempre.setText(_translate("Form", "Siempre"))
        self.label30Dias.setText(_translate("Form", "Últimos 30 Días"))
        self.labelHoy.setText(_translate("Form", "Hoy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
